spring.application.name=STEVEN_ZIPS
server.port=8080

# [도커 TTS 미사용] 외부 TTS 도커(8060) — Google Cloud TTS(tts-key.json) 사용
#tts.service.base-url=http://127.0.0.1:8060
logging.level.kr.or.ddit=info
logging.level.org.springframework.security=debug

# JSP \uBDF0 \uB9AC\uC878\uBC84 \uC124\uC815
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=${DB_URL}
spring.datasource.username=team1_202511F
spring.datasource.password=java
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=20MB

# \uD30C\uC77C \uC5C5\uB85C\uB4DC \uC800\uC7A5(\uBB3C\uB9AC) \uACBD\uB85C \uC124\uC815 \uBC0F \uD658\uACBD\uBCC0\uC218(UPLOAD_PATH) \uC8FC\uC785
# \uC8FC\uC758! \uACBD\uB85C\uC5D0 \uACF5\uBC31\uC774 \uC788\uC73C\uBA74 \uC548 \uB428
# UPLOAD_PATH \uD658\uACBD\uBCC0\uC218\uAC00 \uC874\uC7AC\uD558\uBA74 \uD574\uB2F9 \uACBD\uB85C \uC0AC\uC6A9
# \uC5C6\uC73C\uBA74 \uAE30\uBCF8\uAC12 C:/upload \uC0AC\uC6A9
kr.or.ddit.upload.path=${UPLOAD_PATH:C:/upload}

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=varchar
mybatis.type-aliases-package=kr.or.ddit.vo

# \uC6B0\uB9AC \uD504\uB85C\uC81D\uD2B8 \uAD6C\uC870\uC5D0 \uB9DE\uB294 MyBatis Mapper \uC704\uCE58
mybatis.mapper-locations=classpath:mybatis/mapper/**/*_Mapper.xml

# Google Drive \uD3F4\uB354 ID
google.drive.folder-id=${GOOGLEDRIVE_FOLDER_ID}

kr.or.ddit.jwt.issuer=ddit
kr.or.ddit.jwt.secret_key=${JWT_SECRET_KEY}

# MyBatis Map \uBC18\uD658 \uC2DC NULL \uCEEC\uB7FC\uB3C4 Key \uC720\uC9C0
mybatis.configuration.call-setters-on-nulls=true

# PortOne V1 \uACB0\uC81C \uD14C\uC2A4\uD2B8 \uC124\uC815
portone.imp-code=${PORTONE_IMPCODE}
portone.channel-key=${PORTONE_CHANNEL_KEY}
portone.api-key=${PORTONE_API_KEY}
portone.api-secret=${PORTONE_API_SECRET}

# SMS \uBC1C\uC1A1 \uBAA8\uB4DC
#mock : \uC2E4\uC81C \uBB38\uC790 \uBC1C\uC1A1 \uC5C6\uC774 DB \uC774\uB825\uB9CC \uC800\uC7A5
#sms.sender-type=mock

# solapi : \uC2E4\uC81C \uC194\uB77C\uD53C \uBB38\uC790 \uBC1C\uC1A1
sms.sender-type=solapi

# \uC194\uB77C\uD53C \uC2E4\uC81C \uBC1C\uC1A1 \uC815\uBCF4
# \uBCF4\uC548\uC0C1 \uC2E4\uC81C \uC6B4\uC601\uC5D0\uC11C\uB294 \uBCC4\uB3C4 \uD30C\uC77C \uB610\uB294 \uD658\uACBD\uBCC0\uC218 \uAD00\uB9AC \uAD8C\uC7A5
solapi.api-key=${SOLAPI_API_KEY}
solapi.api-secret=${SOLAPI_API_SECRET}
solapi.from=${SOLAPI_FROM}

# 프로젝트 루트에 있는 .env 파일을 읽어옴 (파일이 없어도 에러를 내지 않도록 optional: 적용)
spring.config.import=optional:file:.env[.properties]